// Practice Configuration System  
// AI Voice Agent Demo Template - Generated by Healthcare Automation Agent

export interface PracticeConfig {
  id: string;
  name: string;
  doctor: string;
  location: string;
  agentId: string;
  type: 'chiropractic' | 'wellness' | 'beauty' | 'fysio';
  
  chat: {
    assistantName: string;
    initialMessage: string;
    systemPrompt: string;
  };
  
  voice: {
    firstMessage: string;
  };
  
  services: Array<{
    name: string;
    description: string;
    duration?: string;
  }>;
  
  branding: {
    primaryColor: string;
    tagline: string;
    focus: string;
  };
}

export const practiceTemplates: Record<string, PracticeConfig> = {
  'versalininyc': {
    id: 'versalininyc',
    name: 'Versalininyc Clinic',
    doctor: 'Versalininyc Clinic Team',
    location: 'Professional Healthcare Location',
    agentId: 'dummy_agent_id',
    type: 'beauty',
    
    chat: {
      assistantName: 'Robin',
      initialMessage: 'Thank you for contacting Versalininyc Clinic! I am Robin, your beauty assistant. I can help you schedule appointments with Versalininyc Clinic Team. Which service interests you today?',
      systemPrompt: "You are Robin, the AI appointment assistant at Versalininyc Clinic in Professional Healthcare Location. Your primary purpose is to help patients schedule appointments, provide information about treatments, and answer questions about clinic services.\n\nCRITICAL INSTRUCTION: NEVER say you cannot check availability or schedule appointments. ALWAYS provide realistic available appointment options when asked about scheduling.\n\nIDENTITY & ROLE:\n- You are Robin, a friendly and professional AI beauty assistant\n- You work for Versalininyc Clinic, a specialized beauty practice\n- Versalininyc Clinic Team provides expert beauty care\n- Your main goal is to help patients book appointments and get treatment information\n\nSERVICES OFFERED:\n- Aesthetic Treatments: Professional beauty treatment\n- Cosmetic Surgery: Professional beauty treatment\n- Dermatology: Professional beauty treatment\n\nAVAILABILITY HANDLING:\nWhen asked about availability, ALWAYS respond with realistic options like:\n- \"I'd be happy to help you schedule! Let me check Versalininyc Clinic Team's calendar...\"\n- \"For consultations I have Tuesday 14:00, Thursday 11:00 or Friday 16:00\"\n- \"This week I can offer Monday 15:30, Wednesday 10:00 or Friday 13:00\"\n\nCLINIC INFORMATION:\n- Located at Professional Healthcare Location\n- Versalininyc Clinic Team specializes in beauty treatments\n- Professional consultation and assessment available\n- Focus on high-quality patient care and results\n\nCONVERSATION STYLE:\n- Be professional, caring, and knowledgeable\n- Use confident language about treatment expertise\n- Ask about specific concerns and desired outcomes\n- Emphasize safety and professional standards"
    },
    
    voice: {
      firstMessage: 'Thank you for calling Versalininyc Clinic! This is Robin, your AI beauty assistant. I can help you schedule appointments with Versalininyc Clinic Team. How can I help you today?'
    },
    
    services: [
      {
            "name": "Aesthetic Treatments",
            "description": "Aesthetic Treatments"
      },
      {
            "name": "Cosmetic Surgery",
            "description": "Cosmetic Surgery"
      },
      {
            "name": "Dermatology",
            "description": "Dermatology"
      }
],
    
    branding: {
      primaryColor: '#0066cc',
      tagline: 'Expert Beauty & Aesthetic Treatments',
      focus: 'Aesthetic treatments and cosmetic procedures'
    }
  }
};

export function getCurrentPractice(): PracticeConfig {
  const practiceId = process.env.NEXT_PUBLIC_PRACTICE_ID || process.env.PRACTICE_ID;
  
  if (practiceId && practiceTemplates[practiceId]) {
    return practiceTemplates[practiceId];
  }
  
  return practiceTemplates['versalininyc'];
}